apiVersion: v1
kind: LimitRange
metadata:
  name: stage-defaults
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 300m
        memory: 384Mi
