apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
namePrefix: prod-
commonLabels:
  app: podinfo
  env: prod
  team: platform
  owner: platform-team
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
