apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-team-label
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-team-label
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - Service
      validate:
        message: "Resources must have a team label."
        pattern:
          metadata:
            labels:
              team: "?*"
