apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-podinfo
  progressDeadlineSeconds: 600
  service:
    port: 9898
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 60
    stepWeight: 20
