apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: podinfo
  env: dev
  owner: platform-team
resources:
  - ../../base
  - image-update.yaml
patches:
  - path: patch-deployment.yaml
