apiVersion: v1
kind: Secret
metadata:
    name: dev-demo-secret
    namespace: dev
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:fLRILW3rOU00NSHiCdsISXVC,iv:mhWm9wB0v3FlSRXY5cp0iFwAkQKKH0N2rqEQgm5C2+s=,tag:c9cgpiVqtCC2zc1I2h9eMw==,type:str]
sops:
    age:
        - recipient: age18yyy3t047y696ptkxn8vp5gs737frjys0sqv8qpcwju53ahnja7qlmeeaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbzI0Q2o2b0ZiNkUyZkRz
            bVc0Nnl2SlpoTGFsRVpZWkhZUTI0Z2lmdkVrCmJMYzdRSVVYbEFLVDN6L3EzZlVN
            Q3RvQnhkZURmbmdzcjlzbWNEOXV5aTAKLS0tIE5JSmRHQ3ZjWC8vSFQzKzVseWVh
            T2VjeHR1dXlaQ0JIOHVzQlJjSkNnZGsKhPdFNj4buaIDfXYJZC3Zl4GiJCuK8ahD
            WdDsHQ0HWVGH13iZcwNLqKkjpBk/xFJzMgiIhtTFIOlA+k1JkNRAxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T07:33:24Z"
    mac: ENC[AES256_GCM,data:AYCzX6m8Vk7P7lP/IhQ3GeT8Dd5QmqzMDcaq1OueNlygg0CKSKfSKmlOTw49+RS/UJEZScExoxeX5sIKSvW+cYU6XmSv9bpQWJEOoewq5uhVG+QLcX/nmFdc9aV3BjNoTlUXrRHl5Kh/Wqm9qXA4H81zxkNXgeFe83gNhpcZOtc=,iv:vNCLGjlgGa42c+dyyn+NPyiu7OMTJFJKgayedquQ2CE=,tag:7YpCpliVnR3Cdtk7of5/Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
